#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "azure-to-slack-webhook"
version = "0.1.0"
authors = ["Kate Goldenring <kate.goldenring@fermyon.com>"]
description = "Webhook that forwards Azure alerts to a Slack Incoming Webhook"

[variables]
slack_webhook_url = { required = true }
azure_alerts_dashboard_url = { default = "" }


[[trigger.http]]
route = "/..."
component = "azure-to-slack-webhook"

[component.azure-to-slack-webhook]
source = "target/wasm32-wasip1/release/azure_to_slack_webhook.wasm"
allowed_outbound_hosts = ["https://hooks.slack.com"]
[component.azure-to-slack-webhook.variables]
slack_webhook_url = "{{ slack_webhook_url }}"
azure_alerts_dashboard_url = "{{ azure_alerts_dashboard_url }}"
[component.azure-to-slack-webhook.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
